export enum IProductTypes {
  OTHER = "OTHER",
  EGG_MILK_PRODUCTS = "EGG_MILK_PRODUCTS",
  FATS_OILS = "FATS_OILS",
  FRUITS = "FRUITS",
  GRAIN_NUTS_BAKING = "GRAIN_NUTS_BAKING",
  HERBS_SPICES = "HERBS_SPICES",
  MEAT_SASUAGE = "MEAT_SASUAGE",
  FISH = "FISH",
  PASTA_RICE = "PASTA_RICE",
  VEGETABLES = "VEGETABLES",
  LEGUMES = "LEGUMES",
}

export default { IProductTypes };
