export enum IRecipeTypes {
  MEAT_SASUAGE = "MEAT_SASUAGE",
  FISH = "FISH",
  VEGETABLES = "VEGETABLES",
  LEGUMES = "LEGUMES",
  EGGS = "EGGS",
  FRUITS = "FRUITS",
  MILK_RECIPE = "MILK_RECIPE",
  GRAIN_NUTS = "GRAIN_NUTS",
  BAKING = "BAKING",
  POULTRY = "POULTRY",
  PASTA = "PASTA",
  RICE = "RICE",
  POTATOES = "POTATOES",
  SOUPS = "SOUPS",
  OTHER = "OTHER",
  DESSERTS = "DESSERTS",
  NONE = "NONE",
}

export default { IRecipeTypes };
