repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, black, --skip, migrations]
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        additional_dependencies: [flake8-django==1.4.0]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy # It will read mypy.ini automatically
        additional_dependencies:
          - celery==5.3.4
          - daphne==4.0.0
          - django==4.2.7
          - django-celery-results==2.5.1
          - django-cors-headers==3.14.0
          - django-filter==22.1
          - django-filter-stubs==0.1.3
          - django-money==3.4.1
          - django-stubs==4.2.7
          - djangorestframework==3.14.0
          - djangorestframework-stubs==3.14.5
          - djangorestframework-camel-case==1.4.2
          - drf-extra-fields==3.4.1
          - drf-yasg==1.21.5
          - drf-yasg-stubs==0.1.4
          - types-requests==2.28.11.13
          - types-redis==4.6.0.11
          - celery-stubs==0.1.3
          - sentry-sdk==1.14.0
          - python-decouple==3.8
          - mysqlclient==2.2.1
