version: "3"
services:
  backend:
    # image: ghcr.io/renefs/cociplan:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    command: gunicorn -b 0.0.0.0 -p 8000 cociplan.wsgi:application  --bind 0.0.0.0:8000
    volumes:
      - logs:/app/logs
      - static:/app/static
      - media:/app/media
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ENV=prod
    expose:
      - 8000
    depends_on:
      - db
  client:
    # image: ghcr.io/renefs/cociplan-client:latest
    build:
      context: .
      dockerfile: docker.client.Dockerfile
    container_name: client
    restart: always
    env_file:
      - ./.env.prod
    environment:
      - NGINX_PORT=8080
    ports:
      - 8080:80
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend
  db:
    image: mariadb:10
    container_name: db
    expose:
      - 3306
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  static:
  media:
  logs:
