# Generated by Django 4.2 on 2023-05-18 07:53

import django.db.models.deletion
import menus.models.recipes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DailyMenu",
                "verbose_name_plural": "Daily Menus",
                "ordering": ["last_updated"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("EGG_MILK_PRODUCTS", "Egg Milk Products"),
                            ("FATS_OILS", "Fats Oils"),
                            ("FRUITS", "Fruits"),
                            ("GRAIN_NUTS_BAKING", "Grain Nuts Baking"),
                            ("HERBS_SPICES", "Herbs Spices"),
                            ("MEAT_SASUAGE", "Meat Sasuage"),
                            ("FISH", "Fish"),
                            ("PASTA_RICE", "Pasta Rice"),
                            ("VEGETABLES", "Vegetables"),
                            ("LEGUMES", "Legumes"),
                            ("OTHER", "Other"),
                        ],
                        default="NONE",
                        max_length=200,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "meal",
                    models.CharField(
                        choices=[("LUNCH", "Lunch"), ("DINNER", "Dinner")], default="LUNCH", max_length=200
                    ),
                ),
                (
                    "meal_temp",
                    models.CharField(choices=[("WARM", "Warm"), ("COLD", "Cold")], default="WARM", max_length=200),
                ),
                ("description", models.JSONField(blank=True)),
                ("notes", models.JSONField(blank=True)),
                ("instructions", models.JSONField(blank=True)),
                ("difficulty", models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ("preference", models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                (
                    "prefered_meal",
                    models.CharField(
                        choices=[("LUNCH", "Lunch"), ("DINNER", "Dinner")], default="LUNCH", max_length=200
                    ),
                ),
                ("is_only_dinner", models.BooleanField(default=False)),
                ("is_only_lunch", models.BooleanField(default=False)),
                ("can_be_dinner", models.BooleanField(default=True)),
                ("can_be_lunch", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "days_of_week",
                    models.CharField(
                        choices=[("WEEK_DAYS", "Week Days"), ("WEEKENDS", "Weekends"), ("ALL", "All")],
                        default="ALL",
                        max_length=200,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("preparation_time", models.IntegerField(blank=True, default=0, null=True)),
                ("servings", models.IntegerField(blank=True, default=0, null=True)),
                ("season_spring", models.BooleanField(default=True)),
                ("season_summer", models.BooleanField(default=True)),
                ("season_autumn", models.BooleanField(default=True)),
                ("season_winter", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to=menus.models.recipes.user_directory_path)),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyMenu",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "friday_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fridays", to="menus.dailymenu"
                    ),
                ),
                (
                    "monday_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="mondays", to="menus.dailymenu"
                    ),
                ),
                (
                    "saturday_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="saturdays", to="menus.dailymenu"
                    ),
                ),
                (
                    "sunday_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sundays", to="menus.dailymenu"
                    ),
                ),
                (
                    "thursday_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="thursdays", to="menus.dailymenu"
                    ),
                ),
                (
                    "tuesday_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tuesdays", to="menus.dailymenu"
                    ),
                ),
                (
                    "wednesday_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wednesdays", to="menus.dailymenu"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Menu",
                "verbose_name_plural": "Daily Menus",
                "ordering": ["last_updated"],
            },
        ),
        migrations.CreateModel(
            name="Side",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.CharField(max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="sides", to="menus.product"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sides", to="menus.recipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Side",
                "verbose_name_plural": "Sides",
                "ordering": ["quantity"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.CharField(max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="ingredients", to="menus.product"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ingredients", to="menus.recipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
                "ordering": ["quantity"],
            },
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="dinner_recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="dinners", to="menus.recipe"
            ),
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="lunch_recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lunches", to="menus.recipe"
            ),
        ),
    ]
