# Generated by Django 4.2 on 2024-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0002_recipe_is_oven_recipe_recipe_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="type",
            field=models.CharField(
                choices=[
                    ("MEAT_SASUAGE", "Meat Sasuage"),
                    ("FISH", "Fish"),
                    ("VEGETABLES", "Vegetables"),
                    ("LEGUMES", "Legumes"),
                    ("EGGS", "Eggs"),
                    ("FRUITS", "Fruits"),
                    ("MILK_RECIPE", "Milk Products"),
                    ("GRAIN_NUTS", "Grain Nuts"),
                    ("BAKING", "Baking"),
                    ("POULTRY", "Poultry"),
                    ("PASTA", "Pasta"),
                    ("RICE", "Rice"),
                    ("POTATOES", "Potatoes"),
                    ("SOUPS", "Soups"),
                    ("OTHER", "Other"),
                    ("DESSERTS", "Desserts"),
                    ("NONE", "None"),
                ],
                default="NONE",
                max_length=200,
            ),
        ),
    ]
