# Generated by Django 4.2 on 2024-07-08 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0004_recipe_is_side_plate_recipe_side_plates"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="side_plates",
            new_name="sides",
        ),
        migrations.DeleteModel(
            name="Side",
        ),
    ]
