# Generated by Django 4.2 on 2024-07-11 06:04

from django.db import migrations, models
import django.db.models.deletion
import menus.models.recipes


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0005_rename_side_plates_recipe_sides_delete_side"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="image",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="sides",
            field=models.ManyToManyField(blank=True, to="menus.recipe"),
        ),
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=menus.models.recipes.user_directory_path,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menus.recipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Image",
                "verbose_name_plural": "Recipe Images",
                "ordering": ["id"],
            },
        ),
    ]
