# Generated by Django 4.2 on 2024-07-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0006_remove_recipe_image_alter_recipe_sides_recipeimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeimage",
            options={
                "ordering": ["recipe"],
                "verbose_name": "Recipe Image",
                "verbose_name_plural": "Recipe Images",
            },
        ),
        migrations.RemoveField(
            model_name="recipeimage",
            name="id",
        ),
        migrations.AlterField(
            model_name="recipeimage",
            name="recipe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="menus.recipe",
            ),
        ),
    ]
