# Generated by Django 4.2 on 2024-07-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0007_alter_recipeimage_options_remove_recipeimage_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="description",
        ),
        migrations.AlterField(
            model_name="recipeimage",
            name="recipe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="image",
                serialize=False,
                to="menus.recipe",
            ),
        ),
    ]
