# Generated by Django 4.2 on 2024-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0008_remove_recipe_description_alter_recipeimage_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="can_be_dinner",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="can_be_lunch",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_only_dinner",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_only_lunch",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="meal",
            field=models.CharField(
                choices=[("LUNCH", "Lunch"), ("DINNER", "Dinner"), ("BOTH", "Both")],
                default="LUNCH",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prefered_meal",
            field=models.CharField(
                choices=[("LUNCH", "Lunch"), ("DINNER", "Dinner"), ("BOTH", "Both")],
                default="LUNCH",
                max_length=200,
            ),
        ),
    ]
