# Generated by Django 4.2 on 2024-07-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0009_remove_recipe_can_be_dinner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailymenu",
            name="dinner_recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dinners",
                to="menus.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="dailymenu",
            name="lunch_recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lunches",
                to="menus.recipe",
            ),
        ),
    ]
