name: Django CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
          mv backend/config/config.sample.py backend/config/config.py
          sed -i -e "s/\/usr\/src\/data\/db.sqlite3/{{env.GITHUB_WORKSPACE}}\backend\/db.sqlite3/g" backend/config/config.py
      - name: Run Tests
        run: |
          coverage run backend/manage.py test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
