name: Docker Build & Publish Backend latest
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish Docker Image (latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push backend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to your Dockerfile and other build context files
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/bocabitlabs/${{ github.repository }}
